### ISSUE TITLE
Fix linter warnings

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis#101]
src/map.js
    1:8    error    "core" is defined but never used                                                               no-unused-vars
    9:13   warning  Missing function expression name                                                               func-names
    9:24   error    Block must not be padded by blank lines                                                        padded-blocks
   11:5    error    Split 'var' declarations into multiple statements                                              one-var
   11:5    error    Unexpected var, use let or const instead                                                       no-var
   14:27   error    Missing trailing comma                                                                         comma-dangle
   32:29   error    Missing trailing comma                                                                         comma-dangle
   37:15   warning  Missing function expression name                                                               func-names
   38:9    error    Split 'var' declarations into multiple statements                                              one-var
   38:9    error    Unexpected var, use let or const instead                                                       no-var
   52:49   error    Block must not be padded by blank lines                                                        padded-blocks
   55:90   error    Missing trailing comma                                                                         comma-dangle
   58:13   error    ["Authorization"] is better written in dot notation                                            dot-notation
   61:14   warning  Missing function expression name                                                               func-names
   65:22   error    Unexpected var, use let or const instead                                                       no-var
   65:22   error    All "var" declarations must be at the top of the function scope                                vars-on-top
   71:28   warning  Missing function expression name                                                               func-names
   71:36   error    Unexpected space before function parentheses                                                   space-before-function-paren
   72:13   error    Unexpected var, use let or const instead                                                       no-var
   77:32   warning  Missing function expression name                                                               func-names
   77:40   error    Unexpected space before function parentheses                                                   space-before-function-paren
   78:13   error    Unexpected var, use let or const instead                                                       no-var
   78:13   error    Split 'var' declarations into multiple statements                                              one-var
   88:43   error    Missing trailing comma                                                                         comma-dangle
   94:26   warning  Missing function expression name                                                               func-names
   94:34   error    Unexpected space before function parentheses                                                   space-before-function-paren
   95:13   error    Unexpected var, use let or const instead                                                       no-var
   95:13   error    Split 'var' declarations into multiple statements                                              one-var
  100:22   error    Unexpected var, use let or const instead                                                       no-var
  100:22   error    All "var" declarations must be at the top of the function scope                                vars-on-top
  120:28   warning  Missing function expression name                                                               func-names
  120:36   error    Unexpected space before function parentheses                                                   space-before-function-paren
  125:29   warning  Missing function expression name                                                               func-names
  125:37   error    Unexpected space before function parentheses                                                   space-before-function-paren
  129:17   error    ["dhis2"] is better written in dot notation                                                    dot-notation
  129:36   error    ["jQuery"] is better written in dot notation                                                   dot-notation
  132:18   error    Closing curly brace does not appear on the same line as the subsequent block                   brace-style
  133:121  warning  Missing function expression name                                                               func-names
  134:124  warning  Missing function expression name                                                               func-names
  135:131  warning  Missing function expression name                                                               func-names
  136:139  warning  Missing function expression name                                                               func-names
  137:142  warning  Missing function expression name                                                               func-names
  138:150  warning  Missing function expression name                                                               func-names
  149:28   warning  Missing function expression name                                                               func-names
  149:36   error    Unexpected space before function parentheses                                                   space-before-function-paren
  150:13   error    Unexpected var, use let or const instead                                                       no-var
  150:13   error    Split 'var' declarations into multiple statements                                              one-var
  154:17   error    callbacks is already declared in the upper scope                                               no-shadow
  167:26   warning  Missing function expression name                                                               func-names
  167:35   error    r is already declared in the upper scope                                                       no-shadow
  168:21   error    Unexpected var, use let or const instead                                                       no-var
  171:18   error    Missing trailing comma                                                                         comma-dangle
  174:27   warning  Missing function expression name                                                               func-names
  181:26   error    Unexpected var, use let or const instead                                                       no-var
  181:26   error    All "var" declarations must be at the top of the function scope                                vars-on-top
  189:33   warning  Missing function expression name                                                               func-names
  190:60   warning  Missing function expression name                                                               func-names
  199:31   warning  Missing function expression name                                                               func-names
  200:22   error    Unexpected var, use let or const instead                                                       no-var
  200:22   error    All "var" declarations must be at the top of the function scope                                vars-on-top
  206:25   warning  Missing function expression name                                                               func-names
  206:33   error    Unexpected space before function parentheses                                                   space-before-function-paren
  207:13   error    Unexpected var, use let or const instead                                                       no-var
  207:13   error    Split 'var' declarations into multiple statements                                              one-var
  213:59   error    Missing trailing comma                                                                         comma-dangle
  217:17   error    "keyUiLocale" is defined but never used                                                        no-unused-vars
  219:17   error    "dateFormat" is defined but never used                                                         no-unused-vars
  238:21   error    Expected indentation of 16 space characters but found 20                                       indent
  239:21   error    Expected indentation of 16 space characters but found 20                                       indent
  240:21   error    Expected indentation of 16 space characters but found 20                                       indent
  240:49   error    Missing trailing comma                                                                         comma-dangle
  241:17   error    Expected indentation of 12 space characters but found 16                                       indent
  246:42   error    Missing trailing comma                                                                         comma-dangle
  257:38   error    Missing trailing comma                                                                         comma-dangle
  264:42   error    Missing trailing comma                                                                         comma-dangle
  271:36   error    Missing trailing comma                                                                         comma-dangle
  278:38   error    Missing trailing comma                                                                         comma-dangle
  281:14   error    All "var" declarations must be at the top of the function scope                                vars-on-top
  281:14   error    Unexpected var, use let or const instead                                                       no-var
  286:15   warning  Missing function expression name                                                               func-names
  287:9    error    Unexpected var, use let or const instead                                                       no-var
  287:9    error    Split 'var' declarations into multiple statements                                              one-var
  290:13   error    "initialize" is defined but never used                                                         no-unused-vars
  291:13   error    gis is already declared in the upper scope                                                     no-shadow
  293:26   warning  Missing function expression name                                                               func-names
  295:17   warning  Unexpected alert                                                                               no-alert
  304:17   warning  Unexpected alert                                                                               no-alert
  311:17   warning  Unexpected alert                                                                               no-alert
  315:13   error    Expected no return value                                                                       consistent-return
  318:26   warning  Missing function expression name                                                               func-names
  318:35   error    gis is already declared in the upper scope                                                     no-shadow
  319:13   error    Split 'var' declarations into multiple statements                                              one-var
  319:13   error    Unexpected var, use let or const instead                                                       no-var
  319:17   error    init is already declared in the upper scope                                                    no-shadow
  339:9    error    Unexpected use of comma operator                                                               no-sequences
  339:22   warning  Missing function expression name                                                               func-names
  340:13   error    Unexpected var, use let or const instead                                                       no-var
  340:13   error    Split 'var' declarations into multiple statements                                              one-var
  352:42   warning  Missing function expression name                                                               func-names
  358:37   error    Missing trailing comma                                                                         comma-dangle
  367:13   error    All "var" declarations must be at the top of the function scope                                vars-on-top
  367:13   error    Unexpected var, use let or const instead                                                       no-var
  372:18   error    Closing curly brace does not appear on the same line as the subsequent block                   brace-style
  375:18   error    Closing curly brace does not appear on the same line as the subsequent block                   brace-style
  382:22   error    Wrap an immediate function invocation in parentheses                                           wrap-iife
  382:22   warning  Missing function expression name                                                               func-names
  383:13   error    Unexpected var, use let or const instead                                                       no-var
  397:77   error    Missing trailing comma                                                                         comma-dangle
  415:22   error    A function with a name starting with an uppercase letter should only be used as a constructor  new-cap
  417:10   error    Block must not be padded by blank lines                                                        padded-blocks
  420:25   warning  Missing function expression name                                                               func-names
  428:14   error    Closing curly brace does not appear on the same line as the subsequent block                   brace-style
  439:5    error    All "var" declarations must be at the top of the function scope                                vars-on-top
  439:5    error    Unexpected var, use let or const instead                                                       no-var
  439:25   error    ["DHIS"] is better written in dot notation                                                     dot-notation
  442:2    error    Block must not be padded by blank lines                                                        padded-blocks
  442:2    error    Newline required at end of file but not found                                                  eol-last

✖ 117 problems (86 errors, 31 warnings)

**Comment by turban** [comment]
I have fixed many of the issues, but fixing all would require to require large parts of the code, which is currently out of scope. The following rule checks are turned off:

  "rules": {
    "func-names": 0,
    "one-var": 0,
    "no-var": 0,
    "vars-on-top": 0,
    "comma-dangle": 0,
    "dot-notation": 0,
    "no-shadow": 0,
    "new-cap": 0
  }

**Comment by Markionium** [comment]
You can disable the linter for certain parts of the code using comments.

http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments
