### ISSUE TITLE
Provide colour scales for thematic layers

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis#105]
Provide colour scales from ColorBrewer: http://colorbrewer2.org
Need to update two legend panels in DHIS 2. 

chroma.js is an alternative if the user is going to select from/to-colors:  https://vis4.net/blog/posts/mastering-multi-hued-color-scales/

![screen shot 2016-04-19 at 11 58 36](https://cloud.githubusercontent.com/assets/548708/14635305/15edf444-0626-11e6-94e0-37a4c3911de7.png)

http://mkweb.bcgsc.ca/brewer/

**Comment by turban** [comment]
These legend dialogs should be replaced: 

![screen shot 2016-05-03 at 12 14 29](https://cloud.githubusercontent.com/assets/548708/14980409/a9733e06-1128-11e6-8a8c-3a5ba8ac4040.png)
![screen shot 2016-05-03 at 12 13 26](https://cloud.githubusercontent.com/assets/548708/14980410/a98c5666-1128-11e6-83a5-d3be4b9fa921.png)

**Comment by larshelge** [comment]
Legend set setup should preferably be moved out of GIS and into maintenance app, as it is used by pivot table and soon charting.

**Comment by Markionium** [comment]
Should be easy enough to integrate into the maintenance app when we have the components for picking the colors.

@turban Interested in creating those components? :)

**Comment by turban** [comment]
For sure @Markionium, especially if I can start playing with React :-)

**Comment by turban** [comment]
chroma.js is an alternative if the user is going to select from/to-colors:  https://vis4.net/blog/posts/mastering-multi-hued-color-scales/

Some React components for picking colors:
http://casesandberg.github.io/react-color/
https://www.mapbox.com/react-colorpickr/example/

Other interesting projects:
https://github.com/mapcraftlabs/mapcraftjs
https://github.com/simple-statistics/simple-statistics (natural breaks support)

npm colorbrewer:
https://www.npmjs.com/package/colorbrewer

**Comment by turban** [comment]
This is now fixed for automatic legends. Still some work do be done for predefined legend sets: https://github.com/dhis2/d2-ui/issues/71
