### ISSUE TITLE
Make all relative periods available

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-gis#130]
Make all relative periods available for thematic and event layers.

Since the period dimension is always filter in GIS, there is in fact no need to constrain this to only single periods (like This year). As an example, add Last 3 months. Analytics will handle this nicely as it is now.

See the Pivot table app > Periods for a reference on which relative periods to support.

For corresponding keywords for relative periods see the docs:

http://dhis2.github.io/dhis2-docs/master/en/developer/html/webapi_date_perid_format.html

![rel](https://cloud.githubusercontent.com/assets/908206/15964240/c3571376-2f17-11e6-8421-f1b3aa989dde.png)

**Comment by turban** [comment]
From Pivot table app:
![screen shot 2016-08-31 at 14 32 13](https://cloud.githubusercontent.com/assets/548708/18128775/c4e8ca76-6f87-11e6-90be-94db2365e5ab.png)

**Comment by turban** [comment]
Fixed in trunk.
