### ISSUE TITLE
Change API endpoints for relocate and swap lat/lng

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis#131]
"Relocate og swap lonlat POSTer en orgunit med oppdaterte koordinater til api/metaData. Bør endres til å poste mot api/organisationUnits/<id>"

**Comment by janhenrikoverland** [comment]
Fixed:

- 2.24 snapshot

https://github.com/dhis2/dhis2-gis/commit/0b97086180b55000660561b8ccc5f9841b96e8e1
