### ISSUE TITLE
Thematic layer low high size not restored on favorite load

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-gis#142]
Thematic layer low high size not restored on favorite load.

Steps
----
- Create a thematic layer where Options > high size and low size is set to some custom values like 10 and 20.
- Save as favorite
- Load favorite
> Options > high size and low size is set to 5 and 15 which are the default values.

**Comment by turban** [comment]
Tested now, at this seems to be fixed by @janhenrikoverland
