### ISSUE TITLE
dashboard plugin, enable/disable layers

### ISSUE THREAD

**Issue by mortenoh** [dhis2/dhis2-gis#144]
For dashboard widgets, the DV plugin allows you to do simple category filtering by clicking on the name of the category.. (enable/disable), maybe something similar could be done with the GIS plugin? it's nice when you are mixing polygons with points etc..

<img width="452" alt="screen shot 2016-08-03 at 19 42 47" src="https://cloud.githubusercontent.com/assets/84345/17375708/7859d0a0-59b2-11e6-8d3d-7b8fc95950bb.png">

**Comment by turban** [comment]
Not currently supported in GIS
