### ISSUE TITLE
GIS start page not loading for French UI locale

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-gis#157]
GIS start page is not loading for French UI locale.

- Go to Profile > User settings
- Set interface language to French
- Load GIS app
- App hangs. Seems to be a problem with property file parsing in dhis2.utils.js.

Console:

![gis](https://cloud.githubusercontent.com/assets/908206/18229838/5f6961b2-7287-11e6-922f-22cfd86d8110.png)

**Comment by jason-p-pickering** [comment]
@turban I suspect it is the single quotes. https://github.com/dhis2/dhis2-gis/blob/master/i18n/i18n_app_fr.properties#L6

Do these need to be escaped?

**Comment by turban** [comment]
@jason-p-pickering, I removed to backslash for these two lines, and then it worked: 

google_hybrid=Google Hybrid\
google_streets=Google Streets\
