### ISSUE TITLE
Replace Ext.js functionality with d2-utilizr and native code

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis#18]
- [x] Ext.isArray -> import isArray from 'd2-utilizr/lib/isArray';
- [x] Ext.isBoolean -> import isBoolean from 'd2-utilizr/lib/isBoolean';
- [x] Ext.isEmpty -> import isEmpty from 'd2-utilizr/lib/isEmpty';
- [x] Ext.isFunction -> import isFunction from 'd2-utilizr/lib/isFunction';
- [x] Ext.isNumber -> import isNumber from 'd2-utilizr/lib/isNumber';
- [x] Ext.isNumeric -> import isNumeric from 'd2-utilizr/lib/isNumeric';
- [x] Ext.isObject -> import isObject from 'd2-utilizr/lib/isObject';
- [x] Ext.isString -> import isString from 'd2-utilizr/lib/isString';
- [x] Ext.Array.clean -> import arrayClean from 'd2-utilizr/lib/arrayClean';
- [x] Ext.Array.contains -> import arrayContains from 'd2-utilizr/lib/arrayContains';
- [x] Ext.Array.difference -> import arrayDifference from 'd2-utilizr/lib/arrayDifference';
- [x] Ext.Array.from -> import arrayFrom from 'd2-utilizr/lib/arrayFrom';
- [x] Ext.Array.pluck -> import arrayPluck from 'd2-utilizr/lib/arrayPluck';
- [x] Ext.Array.sort -> import arraySort from 'd2-utilizr/lib/arraySort';
- [x] Ext.Array.unique -> import arrayUnique from 'd2-utilizr/lib/arrayUnique';

Use native:
- [x] Ext.Array.each -> forEach
- [x] Ext.decode -> JSON.parse
- [x] Ext.encode -> JSON.stringify

**Comment by turban** [comment]
Instead of doing `import {arraySort} from 'd2-utilizr'` you can do `import arraySort from 'd2-utilizr/lib/arraySort'` instead and only load the files you need as the first one includes the whole library and therefore increases your bundle size for no reason.

**Comment by janhenrikoverland** [comment]
You can now do (version 0.2.2):

import arrayDifference from 'd2-utilizr/lib/arrayDifference';
