### ISSUE TITLE
Update HTML for web page embedding

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis#38]
Wait until 2.23 release.

**Comment by turban** [comment]
Web page embedding has not been in place for several releases, I need help from @janhenrikoverland to fix it.

**Comment by janhenrikoverland** [comment]
This is now fixed and works well also with earth engine - except:
- selecting only the earth engine layer will not enable the "embed" menu item, as this layer does not have any features

**Comment by janhenrikoverland** [comment]
Good, thanks @turban
