### ISSUE TITLE
Show event data on click

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis#48]
Show attributes in popup checked in "Programs / Attributes" -> Program -> Select a program -> View program stages -> Select a stage -> Edit

<img width="466" alt="screen shot 2016-03-19 at 18 01 17" src="https://cloud.githubusercontent.com/assets/548708/13900023/acb998a2-edfc-11e5-98c7-07b779841f42.png">

**Comment by turban** [comment]
@larshelge, if I have a program id "eBAyeGv0exc" and a program stage id "Zj7UnCAulEk", how can I get the "Display in reports" attributes from the API? I'm looking for the metadata (id) for the attributes we should show to the user.

**Comment by larshelge** [comment]
Something like this:

https://play.dhis2.org/demo/api/programStages/Zj7UnCAulEk.json?fields=programStageDataElements[displayInReports,dataElement[id,name]]

**Comment by turban** [comment]
Fixed in trunk.
