### ISSUE TITLE
Inconsistent behavior with translated orgunits

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/dhis2-gis#49]
When the database language is set to something other than English (e.g. Burmese) the Orgunit tree is displayed with the correct translations of orgunits. However, when hovering over a geographical feature, the base language is displayed. 

![selection_524](https://cloud.githubusercontent.com/assets/2968061/13844468/34461f8a-ec3a-11e5-9f4b-6499e951b67e.png)

However, when changing the interface language to for example (the language of the translation) the translation is displayed. 
![selection_525](https://cloud.githubusercontent.com/assets/2968061/13844505/5c7f17d6-ec3a-11e5-9061-b43e8409726a.png)

This would seem to be inconsistent as the orgunit translations should be derived from the database language, not the interface language. 

On version 2.22  21920

@janhenrikoverland @turban

**Comment by turban** [comment]
Need to get translated org.units names from geoFeatures endpoint: 
/api/geoFeatures.json?ou=ou:LEVEL-2;ImspTQPwCqd&displayProperty=NAME

Fixed in trunk by @larshelge
