### ISSUE TITLE
Generate demo data for Event layer

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis#52]
200 000 malaria cases in Sierra Leone at lower altitude/along the coast.

**Comment by turban** [comment]
I will generate the latitude and longitude for each new demo event in the programstageinxtance table, but could you @larshelge provide some guidance on how to populate these fields?

- programstageinstanceid - auto increment?
- programinstanceid - which value?
- programstageid - which value?
- duedate - same date or random? 
- executiondate - same date or random?
- organisationunitid - is this from the lowest org.unit level where the event belongs?
- status - which value? 
- completeddate  - same date or random?
- uid - how to generate
- attributeoptioncomboid - which value?

**Comment by larshelge** [comment]
First: lets make this a without-registration program (event-based), meaning there is just one program stage and no tracked entity instance.

programstageinstanceid - nextval('hibernate_sequence'); // get next value from sequence
programinstanceid - there is just one for the program
programstageid - there is just one for the program
duedate - leave as null
executiondate - this is the main event date (legacy column name)
organisationunitid - is this from the lowest org.unit level where the event belongs: yes
status - leave as null (not relevant)
completeddate - leave as null (not relevant)
uid - how to generate - not sure. I do this in java ;) a pg function could be useful. http://stackoverflow.com/questions/3970795/how-do-you-create-a-random-string-in-postgresql
attributeoptioncomboid - set to default option combo. Look in table categoryoptioncombo for one with name "default" (usually the first one).

**Comment by larshelge** [comment]
Simplistic approach to UID generation:

SELECT ('a' || substring(md5(random()::text),0,11)) as uid;

**Comment by turban** [comment]
Fixed.
