### ISSUE TITLE
Loading mask not disappearing on validation error

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-gis#58]
When server returns 409, a warning dialog is displayed when loading a map. When clicking close on the dialog, the loading mask is not finished. Example is loading a event layer map with end date before start date.

![load](https://cloud.githubusercontent.com/assets/908206/14245413/782a903e-fa61-11e5-9cc0-7a1efe23f761.png)

**Comment by turban** [comment]
Fixed in trunk.
