### ISSUE TITLE
Z-order of boundary layer

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/dhis2-gis#68]
![submergedboundarylayer](https://cloud.githubusercontent.com/assets/2968061/14376935/d211c830-fda7-11e5-90f2-fe0e67425c30.jpg)
Reported from an external user. 

Note that the boundary layer appears under the thematic layer. 

It seems the boundary layer should be above the thematic layer, and not be influenced by the opacity of the thematic layer as seen in the image. 

Version: 2.21

**Comment by turban** [comment]
Fixed in trunk (2.23). Will proably not be fixed in earlier versions because of the interaction handling in OpenLayers (thematic layers will not be clickable).
