### ISSUE TITLE
Deleting a legend set (that is linked to data element)

### ISSUE THREAD

**Issue by Markionium** [dhis2/dhis2-gis#73]
When attempting to delete a Legendset that is linked to a data element. The operation fails (with a 500 server error) so not really a app error. However the UI also does not give any feedback.

![image](https://cloud.githubusercontent.com/assets/2134901/14462409/3c115dbe-00c7-11e6-88ae-e4288c4514e0.png)

Reproduce:
+ Open GIS (on demo db)
+ Click _Legends_
+ Try to delete _ANC Coverage_

**Comment by turban** [comment]
@larshelge will fix an error response that we can show to the user.

**Comment by larshelge** [comment]
Fixed in trunk.
