### ISSUE TITLE
Thermatic layer 409 without feedback

### ISSUE THREAD

**Issue by Markionium** [dhis2/dhis2-gis#77]
When attempting to add a _National_ organisation unit layer with a child OU of the root selected.

![image](https://cloud.githubusercontent.com/assets/2134901/14465338/de1d6ea8-00d2-11e6-8ddb-ed3001a882dc.png)

Reproduce
+ Open a fresh GIS
+ Open thermic layer 1
+ Select ANC Indicator / ANC 1 Coverage
+ On the org unit tab select _Select levels_ then select _National_ and select _Bo_. (i presume this selection doesn't make any sense?)

![image](https://cloud.githubusercontent.com/assets/2134901/14465705/3708d470-00d4-11e6-87bf-cbfdbf5c960f.png)

**Comment by turban** [comment]
Check level against selected orgunit level on update click.

**Comment by turban** [comment]
Fix applied: https://github.com/dhis2/dhis2-gis/blob/master/src/app/LayerWidgetThematic.js#L1218-L1221
