### ISSUE TITLE
Deleting a favourite with association does not give any feedback

### ISSUE THREAD

**Issue by Markionium** [dhis2/dhis2-gis#79]
When attempting to delete a favourite with an association no feedback is given.

Reproduce
+ Open GIS
+ Click _Favorites_
+ Attempt to delete _ANC: ANC 2 Coverage_

![image](https://cloud.githubusercontent.com/assets/2134901/14466297/74940678-00d6-11e6-834e-8a1a64f6556e.png)

**Comment by turban** [comment]
I'm now showing the error message from the server:

<img width="420" alt="screen shot 2016-04-12 at 23 09 43" src="https://cloud.githubusercontent.com/assets/548708/14475736/c0a34d30-0103-11e6-9154-a15153a6028e.png">

@larshelge, possible with a more descriptive error message than "DeletionHandler"?

**Comment by larshelge** [comment]
Fixed in trunk and 2.22.
