### ISSUE TITLE
Data element filter selections not restored on favorite load

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-gis#82]
- Create an event map with some data elements with the filter set to some value, e.g. Gender set to Male.
- Save as favorite.
- Load favorite.

> The event layer dialog > data element window: The selection (Gender: Male) is not set back.

This implies that when re-clicking Update, the map content changes, which is unfortunate.

![cases](https://cloud.githubusercontent.com/assets/908206/14469530/594e990a-00e5-11e6-93b0-4843c70547fb.png)

**Comment by turban** [comment]
Duplicate of #12
