### ISSUE TITLE
Event layer org unit tree scrollbar

### ISSUE THREAD

**Issue by janhenrikoverland** [dhis2/dhis2-gis#87]
- Open event layer
- Open organisation unit panel
- Expand the tree out of the visible frame

-> No scrollbar

**Comment by turban** [comment]
Fix: 
```javascript
scroll:false,
autoScroll: false,
viewConfig: {
  style: 'overflow-y:auto'
}
```
https://www.sencha.com/forum/archive/index.php/t-144780.html?s=b3a72bbd82e5cc20417f0b5779439b97
