### ISSUE TITLE
Right clicking the tree to select the sub-units does not disable the default context menu

### ISSUE THREAD

**Issue by Markionium** [dhis2/dhis2-gis#95]
When right clicking on a org unit in the tree to get to the `Select sub-units` option. Both the `Select sub-units` and the default browser context menu show up. The user then needs to click away the default context menu to be able to get to the `Select sub-units` option.

![image](https://cloud.githubusercontent.com/assets/2134901/14524552/394b1386-0239-11e6-8850-8219c51b4365.png)

![image](https://cloud.githubusercontent.com/assets/2134901/14524572/5a9fb5dc-0239-11e6-9020-da1ab8095a1e.png)

**Comment by turban** [comment]
Fixed in trunk.
