### ISSUE TITLE
JS error when opening favourite after searching in a layer

### ISSUE THREAD

**Issue by Markionium** [dhis2/dhis2-gis#96]
+ Add thermatic layer
+ Value type:  Data Element
+ Data Element group: ANC
+ Data Element: ANC 1st visit
+ Period type: Relative
+ Period: Last year
+ For organisation units select org unit groups CHC, CHP.
+ Press update
+ Press the layer icon again and click _Search_
+ Double click Baama CHC

Now click favorites and change to any favorite. The app will keep loading as an error was thrown.

![image](https://cloud.githubusercontent.com/assets/2134901/14524796/5d03734e-023a-11e6-8782-fb39ddfdb1f6.png)

**Comment by turban** [comment]
Fixed in trunk.
